services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ./mlruns:/app/mlruns
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "*"
    networks:
      - rakuten-network  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request;urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    command: >
      sh -c "mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /app/mlruns
      --host 0.0.0.0
      --port 5000"

  ingest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rakuten-ingest
    working_dir: /app
    volumes:
     - ${PROJECT_PATH}:/app
     - ${PROJECT_PATH}/data:/app/data
     - ${PROJECT_PATH}/artifacts:/app/artifacts
    environment:
      PYTHONPATH: /app
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091
    networks:
      - rakuten-network
    command: python /app/scripts/ingest_script.py

  train:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}/artifacts:/app/artifacts
      - ${PROJECT_PATH}/models:/app/models
      - ${PROJECT_PATH}/mlruns:/app/mlruns
    environment:
      MLFLOW_TRACKING_URI: http://host.docker.internal:5000
      PYTHONPATH: /app
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091
    networks:
      - rakuten-network
    depends_on:
      mlflow:
        condition: service_healthy
      pushgateway:
        condition: service_started
    command: python /app/scripts/train_script.py

  predict:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}/data:/app/data
      - ${PROJECT_PATH}/artifacts:/app/artifacts
      - ${PROJECT_PATH}/models:/app/models
      - ${PROJECT_PATH}/predictions:/app/predictions
    environment:
      PYTHONPATH: /app
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091
    networks:
      - rakuten-network
    command: python /app/scripts/predict_script.py

  evaluate:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}/artifacts:/app/artifacts
      - ${PROJECT_PATH}/models:/app/models
      - ${PROJECT_PATH}/reports:/app/reports
    environment:
      PYTHONPATH: /app
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091
    networks:
      - rakuten-network
    depends_on:
      - pushgateway
    command: python /app/scripts/evaluate_script.py

  reload:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ${PROJECT_PATH}:/app
    environment:
      PYTHONPATH: /app
      RAKUTEN_API_URL: http://api:8000
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091
    networks:
      - rakuten-network
    depends_on:
      mlflow:
        condition: service_healthy
      pushgateway:
        condition: service_started
    command: python /app/scripts/reload_script.py

  gateway:
    image: nginx:1.27-alpine
    container_name: rakuten-gateway

    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - rakuten-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rakuten-api
    working_dir: /app
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}/artifacts:/app/artifacts
      - ${PROJECT_PATH}/models:/app/models
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091
    expose:
      - "8000"
    networks:
      - rakuten-network
    depends_on:
      mlflow:
        condition: service_healthy
      pushgateway:
        condition: service_started
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  airflow-postgres:
    image: postgres:16
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-db-volume:/var/lib/postgresql/data
    networks:
      - rakuten-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  x-airflow-common: &airflow-common
    build:
      context: .
      dockerfile: Dockerfile.airflow
    working_dir: /opt/airflow
    environment: &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
      AIRFLOW_UID: 50000
      COMPOSE_PROJECT_NAME: rakuten-mlops
    volumes:
      - ${PROJECT_PATH}:/opt/airflow/project
      - ${PROJECT_PATH}/dags:/opt/airflow/dags
      - ${PROJECT_PATH}/airflow/logs:/opt/airflow/logs
      - ${PROJECT_PATH}/airflow/plugins:/opt/airflow/plugins
      - ${PROJECT_PATH}/airflow/config:/opt/airflow/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rakuten-network
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      airflow-postgres:
        condition: service_healthy

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Rakuten
      --lastname Admin
      --role Admin
      --email admin@rakuten.local
      "
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: rakuten-prometheus
    depends_on:
      - api
      - pushgateway
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - rakuten-network
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:v1.8.0
    expose:
      - "9091"
    networks:
      - rakuten-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: rakuten-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - rakuten-network
    restart: unless-stopped
    
volumes:
  airflow-postgres-db-volume:

networks:
  rakuten-network:
    driver: bridge
